from typing import Protocol, Any, runtime_checkable
from pathlib import Path


@runtime_checkable
class LoggerProtocol(Protocol):
    def info(self, msg: str, *args, **kwargs) -> None: ...
    def error(self, msg: str, *args, **kwargs) -> None: ...
    def warning(self, msg: str, *args, **kwargs) -> None: ...
    def debug(self, msg: str, *args, **kwargs) -> None: ...


@runtime_checkable
class ConfigProtocol(Protocol):
    def get_download_dir(self) -> Path: ...
    def get_db_path(self) -> Path: ...
    def get_logs_dir(self) -> Path: ...
    def get_settings_path(self) -> Path: ...
    def is_packaged_mode(self) -> bool: ...


@runtime_checkable
class DatabaseProtocol(Protocol):
    def load_settings(self) -> dict: ...
    def save_settings(self, settings: dict) -> None: ...
    def load_library(self) -> list: ...
    def save_library(self, library: list) -> None: ...


@runtime_checkable
class CacheProtocol(Protocol):
    def get(self, key: str) -> Any: ...
    def set(self, key: str, value: Any) -> None: ...
    def clear(self, key: str) -> None: ...


@runtime_checkable
class DownloadEngineProtocol(Protocol):
    def start_download(self, url: str, options: dict) -> str: ...
    def get_status(self, dl_id: str) -> dict: ...
    def list_downloads(self) -> list: ...
    def download_action(self, dl_id: str, action: str) -> dict: ...


@runtime_checkable
class SecurityProtocol(Protocol):
    def validate_url(self, url: str) -> bool: ...
    def redact_for_logs(self, data: Any) -> Any: ...


@runtime_checkable
class NetworkPolicyProtocol(Protocol):
    def validate_outbound_target(self, url: str) -> None: ...
